[Environment]::SetEnvironmentVariable('PATH',$env:PATH + ';C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('PI_DATA_ARCHIVE_NAME','radixuspisandbox-centralpiserver.southcentralus.cloudapp.azure.com',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('PI_USER','rdxpisandbox\\sergio.treiger',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('PI_PASSWORD','MooseT4nk',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('E_USER','ben.perez@radixeng.com',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('E_PASSWORD','R@dix.Rocks19',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('E_ORG_ID','1',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('E_DATASET_ID','1',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('E_AGENT_INTERVAL_MIN','1',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('E_BASE_URL','https://evergreening.ean.io/datasets/v1/',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('PI_ATTRIBUTE_DEFINITION','name,pointsource,description,digitalset,engunits,exdesc,future,pointtype,ptclassname,sourcetag,archiving,compressing,span,step,zero,changedate,changer,creationdate,creator,pointid,instrumentag',[EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable('E_STATIC_TOKEN','bold-restaurant-motor',[EnvironmentVariableTarget]::Machine)
